Repository redBorder/cookbook-k2http, pull requests merged in 2024-06, with the labels that each got.

#4 Improvement/fix lint
  resources/attributes/default.rb
  resources/libraries/helper.rb
  resources/providers/config.rb
  resources/recipies/default.rb
  resources/resources/config.rb
Labels: enhancement, size/M, lint, refactor, kind/bug

#5 Release 0.0.3
  .github/workflows/rpm.yml
  CHANGELOG.md
  README.md
  resources/attributes/default.rb
  resources/libraries/helper.rb
  resources/metadata.rb
  resources/providers/config.rb
  resources/recipies/default.rb
  resources/resources/config.rb
Labels: kind/documentation, size/L

#6 adapt the timeout to send in batch
  resources/templates/default/k2http_config.yml.erb
Labels: size/XS
